### ISSUE TITLE
Prefix local CSS vars with `__` in Astro components

### ISSUE THREAD

**Issue by andrezero** [noodlestan/designer#133]
## Why 

In case of layout components local CSS variables leak into child nodes – which can be external to our libraries – so we want to minimise the risk of colliding with variables from third parties.

```css
.xs {
     --typeface-size: var(--dd-viz-typeface-size-xs);
}
```

Improves readability, explicit when consuming them

```css
.typeface .content {
    font-family: var(--dd-typeface-family);
    font-size: var(--_typeface-size);
}
```
 
## Waht 

Prefix all with `_`

```css
.xs {
        --__typeface-size: var(--dd-viz-typeface-size-xs);
}
